"""create core schema

Revision ID: 7222483c812c
Revises:
Create Date: 2026-07-31 16:22:39.842111
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7222483c812c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('email_ciphertext', sa.Text(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email_hash')
    )
    op.create_index(op.f('ix_app_users_organization_id'), 'app_users', ['organization_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name_ciphertext', sa.Text(), nullable=True),
    sa.Column('name_hash', sa.String(length=64), nullable=True),
    sa.Column('email_ciphertext', sa.Text(), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_ciphertext', sa.Text(), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('consent_status', sa.String(length=32), nullable=False),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_org_email_hash', 'candidates', ['organization_id', 'email_hash'], unique=False)
    op.create_index('ix_candidate_org_phone_hash', 'candidates', ['organization_id', 'phone_hash'], unique=False)
    op.create_table('processing_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_safe', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_tasks_input_hash'), 'processing_tasks', ['input_hash'], unique=False)
    op.create_index('ix_task_claim', 'processing_tasks', ['status', 'available_at', 'priority'], unique=False)
    op.create_index('ix_task_org_created', 'processing_tasks', ['organization_id', 'created_at'], unique=False)
    op.create_table('job_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('jd_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_requirement_version_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_org_status_updated', 'job_positions', ['organization_id', 'status', 'updated_at'], unique=False)
    op.create_table('resume_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('malware_status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_files_candidate_id'), 'resume_files', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resume_files_sha256'), 'resume_files', ['sha256'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('resume_file_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_positions.id'], ),
    sa.ForeignKeyConstraint(['resume_file_id'], ['resume_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_job_stage_created', 'job_applications', ['job_id', 'stage', 'created_at'], unique=False)
    op.create_table('job_requirement_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rubric_version', sa.String(length=50), nullable=False),
    sa.Column('weight_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'version_no')
    )
    op.create_index(op.f('ix_job_requirement_versions_job_id'), 'job_requirement_versions', ['job_id'], unique=False)
    op.create_table('resume_parse_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_file_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('normalized_text_storage_key', sa.String(length=500), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['resume_file_id'], ['resume_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_file_id', 'version_no')
    )
    op.create_table('candidate_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('parse_version_id', sa.BigInteger(), nullable=False),
    sa.Column('requirement_version_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('gate_result', sa.String(length=32), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rubric_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('supersedes_evaluation_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['parse_version_id'], ['resume_parse_versions.id'], ),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['job_requirement_versions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_evaluation_id'], ['candidate_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_application_created', 'candidate_evaluations', ['application_id', 'created_at'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('dimension_feedback', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requirement_version_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension_code', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirement_type', sa.String(length=32), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_gate', sa.Boolean(), nullable=False),
    sa.Column('acceptable_alternatives', sa.JSON(), nullable=True),
    sa.Column('evidence_rule', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['job_requirement_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_items_requirement_version_id'), 'requirement_items', ['requirement_version_id'], unique=False)
    op.create_table('evaluation_score_details',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension_code', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('calculation_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['candidate_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_score_details_evaluation_id'), 'evaluation_score_details', ['evaluation_id'], unique=False)
    op.create_table('human_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['candidate_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_evidences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('score_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('parse_version_id', sa.BigInteger(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.String(length=100), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['parse_version_id'], ['resume_parse_versions.id'], ),
    sa.ForeignKeyConstraint(['score_detail_id'], ['evaluation_score_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_evidences')
    op.drop_table('human_decisions')
    op.drop_index(op.f('ix_evaluation_score_details_evaluation_id'), table_name='evaluation_score_details')
    op.drop_table('evaluation_score_details')
    op.drop_index(op.f('ix_requirement_items_requirement_version_id'), table_name='requirement_items')
    op.drop_table('requirement_items')
    op.drop_table('interview_feedback')
    op.drop_index('ix_evaluation_application_created', table_name='candidate_evaluations')
    op.drop_table('candidate_evaluations')
    op.drop_table('resume_parse_versions')
    op.drop_index(op.f('ix_job_requirement_versions_job_id'), table_name='job_requirement_versions')
    op.drop_table('job_requirement_versions')
    op.drop_index('ix_application_job_stage_created', table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_resume_files_sha256'), table_name='resume_files')
    op.drop_index(op.f('ix_resume_files_candidate_id'), table_name='resume_files')
    op.drop_table('resume_files')
    op.drop_index('ix_job_org_status_updated', table_name='job_positions')
    op.drop_table('job_positions')
    op.drop_index('ix_task_org_created', table_name='processing_tasks')
    op.drop_index('ix_task_claim', table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_input_hash'), table_name='processing_tasks')
    op.drop_table('processing_tasks')
    op.drop_index('ix_candidate_org_phone_hash', table_name='candidates')
    op.drop_index('ix_candidate_org_email_hash', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_app_users_organization_id'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
